### ISSUE TITLE
[Bug]: `UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}`

### ISSUE THREAD

**Issue by devioa** [Mikubill/sd-webui-controlnet#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I received this warnings during startup:
`venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}`
`venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}`
I checked the extensions one by one and confirmed that this warning was caused by Controlnet

### Steps to reproduce the problem

just launch the webui then wait it show up

### What should have happened?

no warnings

### Commit where the problem happens

controlnet: 1778e2e32f6f6798d7fffb09809230b83d242983

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --opt-split-attention --deepdanbooru
```

### Console logs

```Shell
venv "D:\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 23d460d6cae4637add3676264d49b74a45422da7
Installing requirements


Launching Web UI with arguments: --xformers --opt-split-attention --deepdanbooru
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet v1.1.147
ControlNet v1.1.147
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading weights [cbfba64e66] from D:\stable-diffusion-webui-ux\models\Stable-diffusion\Anime\Counterfeit.safetensors
Creating model from config: D:\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\stable-diffusion-webui-ux\models\VAE\kl-f8-anime2.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(7): bad-artist, bad-picture-chill-75v, bad_prompt_version2, badhandv4, charturnerv2, easynegative, ng_deepnegative_v1_75t
Model loaded in 3.1s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.7s, apply half(): 0.5s, load VAE: 0.2s, move model to device: 0.4s, load textual inversion embeddings: 0.7s).
D:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
D:\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 13.2s (import torch: 1.4s, import gradio: 0.8s, import ldm: 0.4s, other imports: 0.7s, load scripts: 2.0s, load SD checkpoint: 3.4s, opts onchange: 2.5s, create ui: 1.7s, gradio launch: 0.1s).
```
```


### Additional information

_No response_

**Comment by lllyasviel** [comment]
From log, this is not related to controlnet

**Comment by devioa** [comment]
> From log, this is not related to controlnet

@lllyasviel 
but in fact, when I disable the Controlnet, these warnings disappear
and I have also inquired about this in the [discussions](https://github.com/anapnoe/stable-diffusion-webui-ux/discussions/119) of the webui

**Comment by devioa** [comment]
you should ask me for more detailed information instead of closed this issue directly
this warning does indeed exist, and I have repeatedly checked it one by one
initially, it was caused by the upgrade of Gradio in the webui
but after I reported this issue, the author of webui quickly fixed it
afterward, after the `git pull` to update the webui, I received a new warnings, just which is now of this

**Comment by ljleb** [comment]
should be fixed in #1201 now. possible we can also just remove the option.

**Comment by devioa** [comment]
> should be fixed in #1201 now. possible we can also just remove the option.

thanks!
but, I update just now
the `UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}` still exists
has this not been fixed yet?

**Comment by ljleb** [comment]
there isn't any any `Tab(` that has `open=` inside the parens unfortunately. Maybe related to another extension only running code when controlnet is enabled or installed?

**Comment by lllyasviel** [comment]
this one https://github.com/Mikubill/sd-webui-controlnet/blob/630d3daaf3111b1c5cbc0a8e011946611653dc47/scripts/movie2movie.py#L79?

**Comment by ljleb** [comment]
I didn't see this field in your report above, I just found it.

**Comment by ljleb** [comment]
> this one?

yep

**Comment by ljleb** [comment]
#1202 fixes the other warning.

**Comment by devioa** [comment]
ok i see these warnings are no longer show up
thank you both very much!
