### ISSUE TITLE
[Bug]: RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same

### ISSUE THREAD

**Issue by orfeaus** [Mikubill/sd-webui-controlnet#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When trying to use reference_only on MacOS I get the following error (which wasn't the case on control net 162):

RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same

### Steps to reproduce the problem

1. Go to txt2img and enter a simple prompt.
2. In the control net panel, select a reference_only preprocessor.
3. Add the reference image.
4. Click generate.

### What should have happened?

Should have successfully rendered an image.

### Commit where the problem happens

webui: 5ab7f213
controlnet: 1.1.166

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
Not that I'm aware of.
```

### Console logs

```Shell
Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
ControlNet v1.1.166
ControlNet v1.1.166
Loading weights [9aba26abdf] from /Users/me/Documents/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/deliberate_v2.safetensors
Creating model from config: /Users/me/Documents/stable-diffusion/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0): 
Model loaded in 1.8s (load weights from disk: 0.1s, create model: 0.5s, apply weights to model: 0.5s, apply half(): 0.3s, move model to device: 0.4s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.7s (import torch: 0.8s, import gradio: 0.7s, import ldm: 0.2s, other imports: 0.5s, load scripts: 1.3s, load SD checkpoint: 1.8s, create ui: 1.1s, gradio launch: 0.2s).
Loading preprocessor: reference_only
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.RESIZE
raw_H = 1536
raw_W = 1024
target_H = 768
target_W = 512
estimation = 512.0
preprocessor resolution = 512
  0%|                                                                                                                                          | 0/30 [00:00<?, ?it/s]ControlNet used torch.float32 VAE to encode torch.Size([2, 4, 96, 64]).
  0%|                                                                                                                                          | 0/30 [00:02<?, ?it/s]
Error completing request
Arguments: ('task(lj9pkgcbav5zhs6)', 'Zombie Hannah Arendt, smoking cigarette, rotting face and detailed eyes, best quality', '(glasses), badly drawn, sketch, low quality, cartoon, 3d', [], 30, 0, False, False, 1, 1, 7, 2387179226.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, <controlnet.py.UiControlNetUnit object at 0x2b6732050>, <controlnet.py.UiControlNetUnit object at 0x2b65b6020>, <controlnet.py.UiControlNetUnit object at 0x2b65b4190>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, None, False, None, False, 50, 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, False, 'u2net', False, True, False) {}
Traceback (most recent call last):
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 887, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 135, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_unet.py", line 45, in apply_model
    return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 402, in forward_webui
    return forward(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 362, in forward
    outer.original_forward(x=ref_xt, timesteps=timesteps, context=context)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 807, in forward
    return self.out(h)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 323, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same

Loading preprocessor: reference_only
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.RESIZE
raw_H = 1536
raw_W = 1024
target_H = 768
target_W = 512
estimation = 512.0
preprocessor resolution = 512
  0%|                                                                                                                                          | 0/30 [00:00<?, ?it/s]ControlNet used torch.float32 VAE to encode torch.Size([2, 4, 96, 64]).
  0%|                                                                                                                                          | 0/30 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(oehs8guastcojrd)', 'Zombie Hannah Arendt, smoking cigarette, rotting face and detailed eyes, best quality', '(glasses), badly drawn, sketch, low quality, cartoon, 3d', [], 30, 0, False, False, 1, 1, 7, 2387179226.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, <controlnet.py.UiControlNetUnit object at 0x2b678e9b0>, <controlnet.py.UiControlNetUnit object at 0x2b678de10>, <controlnet.py.UiControlNetUnit object at 0x2b678d690>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, None, False, None, False, 50, 0, 0, 512, 512, False, True, False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5, 'polylines_sharp', 0, False, False, False, False, False, False, 'u2net', False, True, False) {}
Traceback (most recent call last):
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 887, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 135, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_unet.py", line 45, in apply_model
    return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 402, in forward_webui
    return forward(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 362, in forward
    outer.original_forward(x=ref_xt, timesteps=timesteps, context=context)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 807, in forward
    return self.out(h)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 323, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same
```

### Additional information

This was working on control net version 1.1.162 before I updated.

**Comment by steffenr** [comment]
I also get the same error. 
My setup: Macbook Pro M2 Max
webui: 5ab7f213
controlnet: 1.1.166
Model: v1-5-pruned-emaonly
COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate"

On reddit someone suggested to remove the **--no-half-vae ** but this also causes the problem. 
I also tried to set 

Steps to reproduce: 

- use text2image
- load an image into ControlNet/ enable it  and choose **reference_only**
- Error occurs while generating the new image

**Comment by lllyasviel** [comment]
fixed in 1.1.167 https://github.com/Mikubill/sd-webui-controlnet/commit/3445f51c12bddc97fc38d228071cc5c674b11e32

**Comment by hellosascha0** [comment]
> fixed in 1.1.167 [3445f51](https://github.com/Mikubill/sd-webui-controlnet/commit/3445f51c12bddc97fc38d228071cc5c674b11e32)

same error :/

**Comment by gregorio500** [comment]
It still throws the error: Error: NDArray dimension length > INT_MAX.

**Comment by delolat** [comment]
> fixed in 1.1.167 [3445f51](https://github.com/Mikubill/sd-webui-controlnet/commit/3445f51c12bddc97fc38d228071cc5c674b11e32)

using version 1.1.170 and still receiving error.

**Comment by lllyasviel** [comment]
fixed again in 1.1.173 https://github.com/Mikubill/sd-webui-controlnet/commit/d831043cb81e97724ccf9f071da391d479440a77
see if works
help is welcome since I do not have MAC
if it does not work, feel free to edit like my commit and let me know how to make it works since it is just a simple data type problem. see also example of https://github.com/Mikubill/sd-webui-controlnet/commit/d831043cb81e97724ccf9f071da391d479440a77

**Comment by gregorio500** [comment]
I've already updated, but it doesn't help with my Mac M1. When I try to use 'reference only' in ControlNet, it throws the error: "Python quit unexpectedly." I've tried using several models, but the same error occur

**Comment by shaolongju** [comment]
ControlNet used torch.float32 VAE to encode torch.Size.

some error when I apply reference only,but I ran SD on the colab google drive, two days ago was fine. this issue come with the new update since the colab notebook automaticlly updated to 1.1.173

**Comment by zhanpenng** [comment]
I encountered the same problem in ControlNet v1.1.215
