### ISSUE TITLE
Recieving FileNotFoundError: [Errno 2] No such file or directory: stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\cldm_v15.yaml'

### ISSUE THREAD

**Issue by DQL003** [Mikubill/sd-webui-controlnet#133]
Seems this issue popped up when I updated webui. Updating controlnet did not alievate the situation

**Comment by Mikubill** [comment]
Is `cldm_v15.yaml` located in `extensions\sd-webui-controlnet\models\`? Check if any file is missing or invalid.

**Comment by DQL003** [comment]
Yes, the file is there. I'm thinking I should reinstall that specific file to see if that helps. I should also note that one of my attempts to fix the problem was uninstalling and reinstalling the whole extension, but it did not work.

**Comment by Mikubill** [comment]
Maybe specify your controlnet config path in settings panel will help

**Comment by DQL003** [comment]
So I tried what you mentioned earlier and nothing. I'm also posting this screenshot to see if there's anything you can find here.
![Screenshot (633)](https://user-images.githubusercontent.com/120735848/219549458-5eed9874-da1d-4279-aeb7-c0b5e84f4b62.png)

**Comment by Bigfield77** [comment]
I had the same issue when I moved my stable diffusion folder from one drive to another

I had to change the path to the yaml file inside config.json (at the root of the stable diffusion folder)

Re-installing controlnet did not change the path by itself

**Comment by riirxx** [comment]
Thanks, Bigfield77. Your comment help me solve the problem. @Bigfield77

**Comment by Bigfield77** [comment]
Good to hear!

**Comment by smileyuver** [comment]
facing the same issue now and not sure which line to change within config.json file... Can you please tell me?

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/9b19c63e9872e3dc059c07a592bbe83250e8ce79

**Comment by shikhar24022** [comment]
I also faced the same issue while adding controlnet extension

**Comment by flaa2000** [comment]
Yeah I just updated 3mins ago and I'm still getting FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Soshi\\Desktop\\stablediffusion\\stablediffusionwebui\\extensions\\sd-webui-controlnet\\extensions\\sd-webui-controlnet\\models\\cldm_v15.yaml' 

I've changed the path under ControlNet settings 
Config file for Control Net models
extensions\sd-webui-controlnet\models\cldm_v15.yaml
Config file for Adapter models
extensions\sd-webui-controlnet\models\sketch_adapter_v14.yaml

Not sure what else to do.

**Comment by flaa2000** [comment]
I see this in the Config.json file (root of the stable diffusion folder)
Line 190:     "control_net_model_config": "extensions\\sd-webui-controlnet\\models\\cldm_v15.yaml",
Line 191:     "control_net_model_adapter_config": "extensions\\sd-webui-controlnet\\models\\sketch_adapter_v14.yaml",

When I remove the extra \ and save the file and start webui-user I get an error and it wont boot up.

**Comment by Mikubill** [comment]
Use models\sketch_adapter_v14.yaml and models\cldm_v15.yaml as config path and check if any errors occur

**Comment by flaa2000** [comment]
Yes that worked. Thank you

**Comment by flaa2000** [comment]
Another error just came up 

Loading preprocessor: canny
Error running process: C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 655, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\processor.py", line 14, in canny
    from annotator.canny import apply_canny
ImportError: cannot import name 'apply_canny' from 'annotator.canny' (C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\canny\__init__.py)

**Comment by JamesLogan2KB** [comment]
> fixed in [9b19c63](https://github.com/Mikubill/sd-webui-controlnet/commit/9b19c63e9872e3dc059c07a592bbe83250e8ce79)

No, it has not been fixed. I have last version of SD and ControlNet and issue persists. It doesn't detect yaml file when it is clearly there.

**Comment by ippfcox** [comment]
> Another error just came up
> 
> Loading preprocessor: canny Error running process: C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py Traceback (most recent call last): File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\modules\scripts.py", line 386, in process script.process(p, *script_args) File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 655, in process detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b) File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\processor.py", line 14, in canny from annotator.canny import apply_canny ImportError: cannot import name 'apply_canny' from 'annotator.canny' (C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\canny__init__.py)

Hi, have you solved this issue? I have the same issue(cannot import name 'apply_canny' from 'annotator.canny') even when I just installed controlnet. Any advice? Thanks!

**Comment by skullzy77** [comment]
> > fixed in [9b19c63](https://github.com/Mikubill/sd-webui-controlnet/commit/9b19c63e9872e3dc059c07a592bbe83250e8ce79)
> 
> No, it has not been fixed. I have last version of SD and ControlNet and issue persists. It doesn't detect yaml file when it is clearly there.

Same here. I never had any issues until today when it sudden;y started saying the file was missing.

**Comment by ippfcox** [comment]
> > Another error just came up
> > Loading preprocessor: canny Error running process: C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py Traceback (most recent call last): File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\modules\scripts.py", line 386, in process script.process(p, *script_args) File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 655, in process detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b) File "C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\processor.py", line 14, in canny from annotator.canny import apply_canny ImportError: cannot import name 'apply_canny' from 'annotator.canny' (C:\Users\Soshi\Desktop\stablediffusion\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\canny__init__.py)
> 
> Hi, have you solved this issue? I have the same issue(cannot import name 'apply_canny' from 'annotator.canny') even when I just installed controlnet. Any advice? Thanks!

solved, reinstalled sd webui...
