### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by freke70** [Mikubill/sd-webui-controlnet#147]
Suddenly getting this error when booting:

`Error calling: /home/me/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/home/nfrederickx/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/home/me/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 277, in ui
    def svgPreprocess(inputs) -> np.ndarray | _Image.Image | str | Dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Error calling: /home/me/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/home/me/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/home/me/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 277, in ui
    def svgPreprocess(inputs) -> np.ndarray | _Image.Image | str | Dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
`

Also it doesn't seem to load the Models anymore, but it does see them

I also see this when running it using controlnet:

`Error running process: /home/me/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/home/me/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/home/me/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 344, in process
    enabled, module, model, weight, image, scribble_mode, \
ValueError: not enough values to unpack (expected 12, got 0)
`

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/fa35459ff9030b4c8c2ec8b4ccc17c9028a5c2c3

**Comment by ptppan** [comment]
Getting this same issue. Tried installing the latest version of the extension but still getting the error every time I boot
