### ISSUE TITLE
[Bug]: Hires. fix with IP-Adapter - AttributeError: 'dict' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by Miczu** [Mikubill/sd-webui-controlnet#2047]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

IP-Adapter is throwing error when used with Hires. fix
IP-Adapter is working just fine without Hires. fix
Other ControlNet types work fine with Hires. fix enabled (canny, reference, T2I-Adapter).

### Steps to reproduce the problem

1. Go to txt2txt
2. Enable ControlNet and pick IP-Adapter
3. Enable Hires. fix
4. Generate
Bug: console throw AttributeError: 'dict' object has no attribute 'ndim'

### What should have happened?

Should generate an image using IP-Adapter model.

### Commit where the problem happens

webui: 1.6.0
controlnet: 1.1.401 [[fd37e9fc](https://github.com/Mikubill/sd-webui-controlnet/commit/fd37e9fc7ced2c3a39aaa3860916672c8d0fbfe8)]

### What browsers do you use to access the UI ?

Firefox

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--no-half-vae --xformers --skip-torch-cuda-test --opt-split-attention --api
```

### List of enabled extensions

DWPose 
OneButtonPrompt 
a1111-sd-webui-tagcomplete 
adetailer 
canvas-zoom 
sd-dynamic-prompts 
sd-dynamic-thresholding 
sd-infinity-grid-generator-script 
sd-webui-3d-open-pose-editor 
sd-webui-agent-scheduler 
sd-webui-animatediff 
sd-webui-aspect-ratio-helper 
sd-webui-controlnet 
sd-webui-depth-lib 
sd-webui-inpaint-anything 
sd-webui-neutral-prompt 
sd-webui-openpose-editor 
sd-webui-regional-prompter 
sd-webui-supermerger 
stable-diffusion-webui-depthmap-script 
stable-diffusion-webui-pixelization 
ultimate-upscale-for-automatic1111

### Console logs

```Shell
---
2023-09-05 07:54:22,211 - ControlNet - INFO - Loading model from cache: ip-adapter_sd15 [6a3f6166]
2023-09-05 07:54:22,216 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sd15
2023-09-05 07:54:22,216 - ControlNet - INFO - preprocessor resolution = 512
2023-09-05 07:54:22,246 - ControlNet - INFO - ControlNet Hooked - Time = 0.03513145446777344
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(7myktioeydradhn)', 'mage', '', [], 20, 'DPM++ 2M SDE Karras', 1, 1, 6, 512, 512, True, 0.5, 2, '4x_NMKD-Superscale-SP_178000_G', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000222DB709B40>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_sampler': False, 'ad_sampler': 'Euler a', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 12, 95, 'Sawtooth', 0, 'Constant', 0, 4, True, 'MEAN', 'AD', 0.7, False, 0, 16, 8, 'mm_sd_v14.ckpt', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000222E9056680>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000222DE7E34C0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000222EE64EA70>, 0, False, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, '0', '0', False, [], 0.5, 'All Frames', 'Loop', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', 0, False, True, False, True, True, 'Create in UI', False, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', None, None, False, None, None, False, None, None, False, 50, True, False, 0, 'Range', 1, 'GPU', True, False, False, False, False, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 2, 0, '∯boost∯clipdepth∯clipdepth_far∯clipdepth_mode∯clipdepth_near∯compute_device∯do_output_depth∯gen_normalmap∯gen_rembg∯gen_simple_mesh∯gen_stereo∯model_type∯net_height∯net_size_match∯net_width∯normalmap_invert∯normalmap_post_blur∯normalmap_post_blur_kernel∯normalmap_pre_blur∯normalmap_pre_blur_kernel∯normalmap_sobel∯normalmap_sobel_kernel∯output_depth_combine∯output_depth_combine_axis∯output_depth_invert∯pre_depth_background_removal∯rembg_model∯save_background_removal_masks∯save_outputs∯simple_mesh_occlude∯simple_mesh_spherical∯stereo_balance∯stereo_divergence∯stereo_fill_algo∯stereo_modes∯stereo_offset_exponent∯stereo_separation') {}
    Traceback (most recent call last):
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "F:\WIP\ML\1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "F:\WIP\ML\1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 412, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\WIP\ML\1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "F:\WIP\ML\1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "F:\WIP\ML\1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "F:\WIP\ML\1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "F:\WIP\ML\1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "F:\WIP\ML\1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 799, in forward_webui
        raise e
      File "F:\WIP\ML\1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 796, in forward_webui
        return forward(*args, **kwargs)
      File "F:\WIP\ML\1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 445, in forward
        if param.hr_hint_cond is not None and x.ndim == 4 and param.hint_cond.ndim == 4 and param.hr_hint_cond.ndim == 4:
    AttributeError: 'dict' object has no attribute 'ndim'

---
```

**Comment by f-rank** [comment]
Also getting exactly this when Hires. fix is on.

**Comment by lllyasviel** [comment]
will fix soon

**Comment by lllyasviel** [comment]
fixed

**Comment by 3dcinetv** [comment]
what's the solution? I'm also getting this error exclusively with IP-adapter on :
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [600087dbba]

**Comment by Idmon** [comment]
Issue is still prevalent. I updated to the newest commit. Even did a checkout to the dev branch but keep getting this error:
`AttributeError: 'dict' object has no attribute 'shape'`

**Comment by MIDG3Tp3nguin** [comment]
Receiving error also with or without hi-res fix enabled/disabled.

version: [v1.7.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [025b30da6f]

**Comment by ericwenger7** [comment]
No it is NOT fixed in webui 1.6. However launching with --no-half does bypass the issue. Infortunatly the renders gets bad (brown noise or incoherent colors) after a while with this setting, so its not a true solution.
