### ISSUE TITLE
[Bug]:  openpose dosent work, no effect

### ISSUE THREAD

**Issue by Yuhyeong** [Mikubill/sd-webui-controlnet#2101]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/1f48a470-de44-43e3-8a93-5c65350e1713)

no matter which preprocesser or model i choose, the result has nothing to do with the pose extracted by openpose.

I select the controlnet weight range from 0.5 to 1.5, it has a little bit change but wired effect. 

Am i doing somgthing wrong? thank u for any helpful suggestions! 

### Steps to reproduce the problem

No special steps

### What should have happened?

--no-half-vae --skip-version-check --enable-insecure-extension-access --xformers

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

No

### Console logs

```Shell
No warning of error
```

**Comment by lllyasviel** [comment]
may related https://github.com/Mikubill/sd-webui-controlnet/issues/2092
will take a look in the next maintain

**Comment by lllyasviel** [comment]
see if fixed in 1.0.410

**Comment by XiangjiBU** [comment]
> see if fixed in 1.0.410

I met the same problem, and I just update, problem not solved ! but it become worse, the put image ares disappeared in "img2img" mode

**Comment by XiangjiBU** [comment]
> see if fixed in 1.0.410
in ‘img2img’ mode, it appears like this
![截图 2023-09-11 16-26-32](https://github.com/Mikubill/sd-webui-controlnet/assets/45818685/f396af04-99af-401d-b5ed-834c4a82b702)

**Comment by Yuhyeong** [comment]
> see if fixed in 1.0.410

sry, it seems no effect. 

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/7cebd46d-efe7-4d1d-99eb-58847f4e96af)

**Comment by lllyasviel** [comment]
1. check `upload independent control image` in img2img
2. kohya openpose only support "openpose" without "_full", and it does not support "pixel perfect"

**Comment by Yuhyeong** [comment]
# before this reply im writting
> 1. check `upload independent control image` in img2img
> 2. kohya openpose only support "openpose" without "_full", and it does not support "pixel perfect"

in .410, i also test the depth mode with diffuser and kohya, they all extract correct depth map, but only the diffuser depth mode correctly works in generation.

so its okay to say that the controllite model has something wrong. But the openpose of controlnet is the same, 

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/213378f9-44e5-4d9c-90ea-b4b76e2bec08)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/7f0c828c-714a-413b-8263-a456160284d8)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/118cfccf-4b2a-4d3b-936b-ca0f2f63db68)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/0a3f9ed8-e5e1-4d22-be66-2395025ac8c0)

# After the reply
> 1. check `upload independent control image` in img2img
> 2. kohya openpose only support "openpose" without "_full", and it does not support "pixel perfect"


thank u for the helpful suggestions! it really helps.
but if it is possible to fix? 

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/a0cecb79-d5c3-4b10-bb9c-be1ba97b1cc7)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/70f954d0-e0e6-47cb-9eb5-c84df1f139a6)
## without "_full"
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/35eaead0-3ca9-4cdb-8a78-1c6f3924eefa)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/49343045/e59372a5-0a63-4814-9e36-6aa0669c2bf7)

**Comment by lllyasviel** [comment]
- if it is possible to fix?

no. we do not own community models.

**Comment by XiangjiBU** [comment]
> 1. check `upload independent control image` in img2img
> 2. kohya openpose only support "openpose" without "_full", and it does not support "pixel perfect"

solved, thanks!!

**Comment by oliverban** [comment]
Which XL controlnet model supports the dw_openpose_full one? Is there any? That one has the face and the hands already built in and is the best one at finding poses!

**Comment by oliverban** [comment]
> > 1. check `upload independent control image` in img2img
> > 2. kohya openpose only support "openpose" without "_full", and it does not support "pixel perfect"
> 
> solved, thanks!!

Yes, this one does work, but it is far inferior to dw_op_full, I'd love for that to be supported!
